# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: List all available tasks
    silent: true
    cmds:
      - task --list

  dev:
    desc: Set up the development environment
    cmds:
      - uv sync --all-extras --dev

  test:
    desc: Run the unit tests
    sources:
      - pyproject.toml
      - uv.lock
      - "**/*.py"
    cmds:
      - uv run pytest -vv --cov --doctest-modules

  fmt:
    desc: Format all the things
    sources:
      - pyproject.toml
      - uv.lock
      - "**/*.py"
    cmds:
      - uv run ruff format .

  lint:
    desc: Run linting
    sources:
      - pyproject.toml
      - uv.lock
      - "**/*.py"
    cmds:
      - uv run ruff check .
      - uv run mypy

  docs:
    desc: Build the documentation
    sources:
      - pyproject.toml
      - uv.lock
      - "**/*.py"
      - docs/src/**/*
      - docs/img/**/*
    cmds:
      - uv run mkdocs build --clean

  check:
    desc: Run all the checks
    sources:
      - pyproject.toml
      - uv.lock
      - "**/*.py"
    cmds:
      - task: test
      - task: fmt
      - task: lint
