name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: release
  cancel-in-progress: false # Only 1 release job can run at a time

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Existing Tags
        run: git fetch --force --tags

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Parse Release Version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish Release Notes
        uses: release-drafter/release-drafter@v6
        with:
            version: ${{ steps.version.outputs.version }}
            publish: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set Up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Deploy Docs to GitHub Pages
        run: |
          uv run mkdocs build --clean
          uv run mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build Python Package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
