name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        shell: bash # Setting shell gets us nice things like pipefail
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Get uv Cache Dir
        id: cache
        run: |
          echo "dir=$(uv cache dir)"
          echo "dir=$(uv cache dir)" >> $GITHUB_OUTPUT

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ${{ steps.cache.outputs.dir }}
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Set Git Config for Copier
        run: |
          git config user.email "test@github-actions.com"
          git config user.name "GitHub Actions"

      - name: Run Unit Tests
        run: uv run pytest -vv --color yes

      - name: Minimize uv cache
        run: uv cache prune --ci
